### PR TITLE
Revert "manifests/image-references: add kube-etcd-signer-server"

### PR DESCRIPTION
**Pull request by hexfusion**
This reverts commit a1f5d26ee2b902a42dc89797dfbe6de4c6d65d1b.

### CODE REVIEW

**Comment by wking** [comment]
/lgtm

We'll take another run at this next week once we've got an image in https://github.com/openshift/ocp-build-data  CC @deads2k, @mfojtik, @sttts, ART builds will be broken until this lands, please take a look.

**Comment by wking** [comment]
CC @smarterclayton too, since it looks like you [manually added `approved`][1] to #20 despite not being an owner ;).

[1]: https://github.com/openshift/cluster-bootstrap/pull/20#event-2207353938

**Comment by wking** [comment]
[e2e-aws][1]:

```
error: could not run steps: release "release-latest" failed: pod release-latest was already deleted
```

/retest

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_cluster-bootstrap/21/pull-ci-openshift-cluster-bootstrap-master-e2e-aws/129/build-log.txt

**Comment by smarterclayton** [comment]
I'm a product owner :)

**Comment by wking** [comment]
All green here.  Not having this in is breaking ART builds, right?

**Pull request merged**
