### PR TITLE
Bug 1855628: bump golang.com/x/text and switch to go-mod and build-machinery

### PR DESCRIPTION
**Pull request by sttts**

### CODE REVIEW

**Comment by eranco74** [comment]
@sttts I took a look at this failure.
test failed due to:
`Bootstrap failed to complete: failed to wait for bootstrapping to complete: timed out waiting for the condition`
But clusterversion and clusteroperators look good:
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-bootstrap/37/pull-ci-openshift-cluster-bootstrap-master-e2e-aws/1346093711796211712/artifacts/e2e-aws/gather-extra/oc_cmds/clusterversion

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-bootstrap/37/pull-ci-openshift-cluster-bootstrap-master-e2e-aws/1346093711796211712/artifacts/e2e-aws/gather-extra/oc_cmds/clusteroperators

I can't seem to find the bootstrap config map the installer is waiting for
`NewListWatchFromClient(client.CoreV1().RESTClient(), "configmaps", "kube-system", fields.OneTermEqualSelector("metadata.name", "bootstrap"))`
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-bootstrap/37/pull-ci-openshift-cluster-bootstrap-master-e2e-aws/1346093711796211712/artifacts/e2e-aws/gather-extra/configmaps.json

any idea where I can find the installer log-bundle-20210104144437.tar.gz?

**Comment by eranco74** [comment]
Found the issue:
`
Jan 07 08:44:28 ip-10-0-60-145 bootkube.sh[51405]: All self-hosted control plane components successfully started
Jan 07 08:44:29 ip-10-0-60-145 bootkube.sh[51405]: I0107 08:44:29.951471       1 request.go:645] Throttling request took 1.126832486s, request: GET:https://localhost:6443/apis/route.openshift.io/v1?timeout=32s
Jan 07 08:44:36 ip-10-0-60-145 bootkube.sh[51405]: [#1] context canceled
Jan 07 08:44:36 ip-10-0-60-145 bootkube.sh[51405]: Sending bootstrap-success event.Tearing down temporary bootstrap control plane...
Jan 07 08:44:36 ip-10-0-60-145 bootkube.sh[51405]: Error: context canceled
`
It's trying to send the bootstrap-success event with a canceled context.
Fixed here - https://github.com/openshift/cluster-bootstrap/pull/51/commits/0af00c85570d3c1d7a8d5db795da771d44bc23ff

**Comment by sttts** [comment]
/retest

Infra?

**Pull request merged**
